FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt-get update && apt-get install -y \
  build-essential \
  gcc-8 \
  g++-8 \
  cmake \
  doxygen \
  graphviz \
  telnet \
  netcat \
  tmux \
  clang-format-6.0 \
  libpcap-dev \
  && rm -rf /var/lib/apt/lists/*

CMD ["bash", "-l"]
